version: "3.2"

services:

  server:
    build: ./server
    container_name: student_server
    restart: always
    expose:
      - 5000

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "5000:5000"  
  
  client:
    build: ./client   
    container_name: student_client
    expose:
      - 8000
    ports:
      - "8000:8000"
  
  
